### ISSUE TITLE
Latest build reports 695p signal on some devices

### ISSUE THREAD

**Issue by codemasterv** [zwenergy/gbaHD#2]
Some devices like my Sony TV, Samsung TV and Elgato HD 60 Pro report a 695p signal and refuse to display.

Other devices such as my Toshiba TV and  report the signal as 720p and works fine

On the previous build it worked on everything but the Samsung

Edit: Fixed in 01/27 update.

**Comment by zwenergy** [comment]
I tried to fix it in the current commit. Is it working for you again?

**Comment by codemasterv** [comment]
yep just popped in to makrk as resolved. Thanks for the update!
