### ISSUE TITLE
How to select 480p output? 

### ISSUE THREAD

**Issue by unmaker64** [zwenergy/gbaHD#26]
Sorry for the noob question but I can't figure out how to set the output to 480p. The only options I see are 720p and 1080p. Thanks 

![480p](https://user-images.githubusercontent.com/110065276/212765813-52023e54-62a7-4273-9197-5abb2b29c74f.png)

**Comment by zwenergy** [comment]
480p is not included by the ManCloud shield by default, as the ESP32 only has enough memory to store 2 bitstreams at the same time. You can download the 480p bitstream from this repo, rename it to either replace the 720p bitstream or 1080p bitstream and place it onto the SD card. Here's more information on that
https://github.com/gbaHD/GBAHD-Shield/wiki/nicetoknowmisc
