### ISSUE TITLE
Color Issues on GB Classic Games

### ISSUE THREAD

**Issue by wengolsky** [zwenergy/gbaHD#27]
Hello,

first sorry for my english... its not the best ;)

i got issues with colors in gameboy classic games like pokemon blue or kirbys dreamland.
but only some colors are wrong (for example in pokemon blue the cities arent changing colors as they should do, or kirby itself is yellow instead pink), some other parts got the right color.
this only happens in classic games, my gameboy color and advance games are all pretty right colored.

so i think its not the hdmi connection... dont got any other idea.

i also re-soldered cpu and ram chip, everything works fine (running smooth, saving game is working). but it doesnt solved the color issue.

anyone similar experiences or can help me?

**Comment by zwenergy** [comment]
Can you take some pictures? And what gbaHD project are you using?

**Comment by wengolsky** [comment]
i use the gba hd upcycle shield
after long research i found out that this was my mistake. many old gb classic games like pokemon red and blue dont have colors, so my gbahd project works fine. thanks
