### ISSUE TITLE
1.4A OSD not working

### ISSUE THREAD

**Issue by unmaker64** [zwenergy/gbaHD#30]
Hi I've just updated the firmware to the latest 1.4A via the OTA. Now I'm unable to access the OSD. I'm using the Mancloud shield

![image](https://github.com/zwenergy/gbaHD/assets/110065276/d35a3fb2-0cab-436a-8a84-c2f4387b2010)

**Comment by DorDur215** [comment]
I am having the same issue.

I've updated to 1.4A and when I try to open the OSD it doesn't open and my buttons stop responding until I press START again.

I am also using ManCloud's Shield.

**Comment by unmaker64** [comment]
It works now after updating the ESP Application. Thank you very much for your hard work
