### ISSUE TITLE
Is it possible to completely disable the WebUI

### ISSUE THREAD

**Issue by unmaker64** [zwenergy/gbaHD#33]
Hello,

Currently with 1.6.1 firmware random resets are far less common but it seems there's still a roughly 1 to 3% chance that a reset will occur within the first 15 minutes of the console being powered on. Although the odds are low, I would prefer that there's a 0% chance of a reset occurring. As I understand it, a bug with the WebUI is to blame for the resets. So I was wondering if it's possible, through firmware or with the addition of a new setting, to disable the WebUI for the time being until the reset bug is fully resolved. 

Many thanks

**Comment by zwenergy** [comment]
Yes, that should be possible. Yet, this repository is actually for the FPGA FW only, the WebUI FW is part of the gbaHD shield over here:
https://github.com/gbaHD/GBAHD-Shield

Please open the issue over there :) .
