### ISSUE TITLE
The first column of pixels is too wide.

### ISSUE THREAD

**Issue by ChristopherHale** [zwenergy/gbaHD#4]
The first column of pixels appears to be drawn 1.5 to 2 times the normal width of a pixel and the last column of pixels appears to be partially cut off or thinner. I've attached a photo from the Advance Wars editor screen, notice the left edge of the mountains when they're against the edge of the screen compared to when they're away from the edge of the screen.

![IMG_2885](https://user-images.githubusercontent.com/8281945/113925205-99270e80-979f-11eb-8529-1b1ef1a31b00.JPG)

![IMG_2884](https://user-images.githubusercontent.com/8281945/113925234-a512d080-979f-11eb-8230-e76cf761fc3b.JPG)

**Comment by ChristopherHale** [comment]
I’m looking into another issue right now but I noticed this extra wide column is misaligning the pixels to the pixel grid effect.

**Comment by ChristopherHale** [comment]
![Uploading image.jpg…]()

**Comment by ChristopherHale** [comment]
After counting the pixels the first pixel of each line is 9 pixels wide instead of the 6 pixels thereafter. The last pixel in the row is now 3 pixels wide and the pixel grid effect is chopping the pixels down the middle instead of being drawn between the pixels.

**Comment by ChristopherHale** [comment]
Here are some more examples with the pixel grid turned on and I'm using a different display. The pixel grid does appear to be positioned correctly with the pixels being shifted partially to the right underneath it. Take note of the lettering and the orange pixels on the mountains. I tried looking through the FPGA code but I didn't see anything that jumps out at me but I'm guessing
 it happens sometime before the pixel grid effect is applied.

![IMG_2998](https://user-images.githubusercontent.com/8281945/117523953-f9ac9580-af6f-11eb-8ff6-03731b6adcc8.JPG)
![IMG_2994](https://user-images.githubusercontent.com/8281945/117523958-fb765900-af6f-11eb-8f61-fb6242f72ff7.JPG)
![IMG_2995](https://user-images.githubusercontent.com/8281945/117523959-fc0eef80-af6f-11eb-8384-4f150f078b67.JPG)
![IMG_2996](https://user-images.githubusercontent.com/8281945/117523961-fca78600-af6f-11eb-958f-e67426d820d0.JPG)
![IMG_2997](https://user-images.githubusercontent.com/8281945/117523963-fdd8b300-af6f-11eb-95f8-012e3b23e242.JPG)

**Comment by bkoropoff** [comment]
@zwenergy this bug should be fixed by #11

**Comment by ChristopherHale** [comment]
Awesome! Thanks!
